server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commentdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:database

  application:
    name: COMMENT-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka