server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka

#  cloud:
#    gateway:
#      routes:
#        - id: USER-SERVICE
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user/**
#
#        - id: POST-SERVICE
#          uri: lb://POST-SERVICE
#          predicates:
#            - Path=/post/**
#
#        - id: COMMENT-SERVICE
#          uri: lb://COMMENT-SERVICE
#          predicates:
#            - Path=/comment/**

